import type { Location } from '@/types/db';

/**
 * De acht uitdeellocaties. Deze lijst staat ook in de database (zie
 * supabase/migrations/20260908150100_seed_locations.sql) en wordt daar vandaan geladen zodra er
 * internet is. Deze kopie is de terugval: de locatiepagina en de keuze bij
 * aanmelden werken zo ook bij een eerste start zonder verbinding.
 *
 * Weekdag volgens Postgres/JavaScript: 0 = zondag, 4 = donderdag, 5 = vrijdag.
 */
export const FALLBACK_LOCATIONS: Location[] = [
  {
    id: 'hoofddorp',
    slug: 'hoofddorp',
    name: 'Hoofddorp',
    venue: 'Voedseldepot',
    street: 'Dirk Storklaan 63A',
    postcode: '2132 PX',
    city: 'Hoofddorp',
    weekday: 5,
    opens_at: '10:00',
    closes_at: '13:00',
    phone: '06 33 41 28 07',
    latitude: 52.3067,
    longitude: 4.6774,
    active: true,
    sort_order: 1,
  },
  {
    id: 'badhoevedorp',
    slug: 'badhoevedorp',
    name: 'Badhoevedorp',
    venue: 'Het Dorpshuis',
    street: 'Snelliuslaan 35',
    postcode: '1171 CZ',
    city: 'Badhoevedorp',
    weekday: 5,
    opens_at: '09:00',
    closes_at: '09:30',
    phone: '06 21 54 23 83',
    latitude: 52.3405,
    longitude: 4.7796,
    active: true,
    sort_order: 2,
  },
  {
    id: 'zwanenburg',
    slug: 'zwanenburg',
    name: 'Zwanenburg',
    venue: 'Protestantse Kerk',
    street: 'Wilhelminastraat 15',
    postcode: '1165 HA',
    city: 'Halfweg',
    weekday: 5,
    opens_at: '09:00',
    closes_at: '09:45',
    phone: '06 29 96 46 44',
    latitude: 52.3866,
    longitude: 4.7414,
    active: true,
    sort_order: 3,
  },
  {
    id: 'spaarndam',
    slug: 'spaarndam',
    name: 'Spaarndam',
    venue: 'Dorpscentrum Spaarndam',
    street: 'Ringweg 36',
    postcode: '2064 KK',
    city: 'Spaarndam',
    weekday: 4,
    opens_at: '15:30',
    closes_at: '16:30',
    phone: '06 28 83 74 51',
    latitude: 52.4131,
    longitude: 4.6803,
    active: true,
    sort_order: 4,
  },
  {
    id: 'vijfhuizen',
    slug: 'vijfhuizen',
    name: 'Vijfhuizen',
    venue: 'Dorpshuis d’Oude Waterwolf',
    street: 'Kromme Spieringweg 436',
    postcode: '2141 AN',
    city: 'Vijfhuizen',
    weekday: 5,
    opens_at: '10:30',
    closes_at: '11:30',
    phone: '06 54 60 19 20',
    latitude: 52.3646,
    longitude: 4.6606,
    active: true,
    sort_order: 5,
  },
  {
    id: 'nieuw-vennep',
    slug: 'nieuw-vennep',
    name: 'Nieuw Vennep',
    venue: 'Gebouw De Rank',
    street: 'Eugenie Previnaireweg 14',
    postcode: '2151 BE',
    city: 'Nieuw Vennep',
    weekday: 5,
    opens_at: '08:00',
    closes_at: '10:00',
    phone: '06 44 72 42 95',
    latitude: 52.2662,
    longitude: 4.6318,
    active: true,
    sort_order: 6,
  },
  {
    id: 'lisserbroek',
    slug: 'lisserbroek',
    name: 'Lisserbroek',
    venue: 'Dorpshuis De Meerkoet',
    street: 'Krabbescheerstraat 1',
    postcode: '2165 XG',
    city: 'Lisserbroek',
    weekday: 4,
    opens_at: '15:30',
    closes_at: '16:30',
    phone: '06 83 55 67 28',
    latitude: 52.2494,
    longitude: 4.5636,
    active: true,
    sort_order: 7,
  },
  {
    id: 'rijsenhout',
    slug: 'rijsenhout',
    name: 'Rijsenhout',
    venue: 'Ontmoetingskerk',
    street: 'Werf 2',
    postcode: '1435 KP',
    city: 'Rijsenhout',
    weekday: 5,
    opens_at: '08:30',
    closes_at: '09:30',
    phone: '06 14 18 19 00',
    latitude: 52.2489,
    longitude: 4.7286,
    active: true,
    sort_order: 8,
  },
];
